version: '3.9'
services:
  dddddddd:
    build:
      context: "."
      dockerfile: Dockerfile.deploy
    image: ghcr.io/riatre/aliyunctf-dddddddd:latest
    ports:
      - "1337:5000/tcp"
    privileged: true
    read_only: true
    restart: unless-stopped
    volumes:
      - type: bind
        source: $PWD/flag
        target: /srv/flag_inside/flag
        read_only: true
