version: "3.9"

services:
  redis:
    image: redis:7.0.10-alpine3.17
    command: redis-server --save 1 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - redis-data:/data
  web:
    image: ghcr.io/riatre/aliyunctf-2023-warmup-checkin:latest
    build: .
    restart: unless-stopped
    ports:
      - "80:80/tcp"
    environment:
      REDIS_URL: redis://redis/0
    volumes:
      - type: bind
        source: $PWD/.env
        target: /app/.env
        read_only: true
    depends_on:
      - redis

volumes:
  redis-data: 
